Fix argument parsing when there is no extra options

diff --git a/bin/unittest-testcase b/bin/unittest-testcase
--- a/bin/unittest-testcase
+++ b/bin/unittest-testcase
@@ -3,17 +3,18 @@
 title=""
 points=0
 skip=0
-while [ -z "${1%%-*}" ]; do
+while [ "$1" ]; do
     case "$1" in
         -t|-n) title=$2 ;;
         -p) points=$2 ;;
         -s|-e) skip=$2 ;;
         --) shift ; break ;;
-        *)
-            echo "ERROR: Invalid option $1" >&2
+        -*)
+            echo "ERROR: Invalid option '$1' for $0" >&2
             echo "usage: $0 [-t title] [-p points_on_success] [-s skip] prog arg1 arg2..." >&2
             exit 64
             ;;
+        *) break ;;
     esac
     shift 2
 done
